import { Project, Skill, ExperienceItem, Pillar, StatBadge, Testimonial } from './types';

export const PERSONAL_INFO = {
  name: 'مهندس / عبد الله الشمري',
  title: 'مهندس واجهات برمجية وخبير تجربة المستخدم',
  englishTitle: 'Principal Frontend Architect & UI/UX Specialist',
  bio: 'مهندس برمجيات شغوف يمتلك أكثر من 6 سنوات من الخبرة المتخصصة في هندسة الواجهات المعقدة والتطبيقات التفاعلية عالية الأداء. أجمع بين الرؤية التصميمية الزجاجية والأكواد النظيفة لبناء تجارب رقمية استثنائية.',
  location: 'الرياض، المملكة العربية السعودية',
  email: 'contact@alshammari.dev',
  phone: '+966 50 123 4567',
  availability: 'متاح للمشاريع الريادية والاستشارات البرمجية 🟢',
  github: 'https://github.com',
  linkedin: 'https://linkedin.com',
  twitter: 'https://x.com',
  dribbble: 'https://dribbble.com',
  resumeUrl: '#',
};

export const STAT_BADGES: StatBadge[] = [
  {
    id: 'exp',
    label: 'سنوات الخبرة',
    value: '+6',
    subtext: 'في تطوير واجهات Web & App',
    iconName: 'Award',
  },
  {
    id: 'projects',
    label: 'مشروع منجز',
    value: '+38',
    subtext: 'تطبيقات منصات وحلول متكاملة',
    iconName: 'FolderGit2',
  },
  {
    id: 'satisfaction',
    label: 'رضا العملاء',
    value: '100%',
    subtext: 'تقييم ممتاز في الأداء والجودة',
    iconName: 'Star',
  },
  {
    id: 'performance',
    label: 'معدل كفاءة الكود',
    value: '99.8%',
    subtext: 'معايير Lighthouse للسرعة والأمان',
    iconName: 'Zap',
  },
];

export const WORK_PILLARS: Pillar[] = [
  {
    id: 'precision',
    title: 'الدقة في التنفيذ',
    subtitle: 'Pixel perfection & UI fidelity',
    iconName: 'Target',
    description: 'تحويل التصاميم الرقمية المعقدة إلى واجهات حية بدقة متناهية مع مراعاة كافة التوافقات الاستجابية وحركات الملاحة.',
  },
  {
    id: 'creativity',
    title: 'التفكير الإبداعي',
    subtitle: 'Innovative problem solving',
    iconName: 'Lightbulb',
    description: 'ابتكار أساليب تفاعلية حديثة واستخدام التأثيرات الزجاجية والهندسية لرفع مستوى اندماج المستخدم وتسهيل التجربة.',
  },
  {
    id: 'clean_code',
    title: 'كتابة كود نظيف وقابل للتوسع',
    subtitle: 'Modular Architecture & Modern React',
    iconName: 'Code2',
    description: 'اعتماد أفضل ممارسات TypeScript والهندسة البرمجية النمطية لضمان سهولة الصيانة والتوسع وسرعة التحميل.',
  },
  {
    id: 'commitment',
    title: 'الالتزام بالحوكمة والمواعيد',
    subtitle: 'Agile Delivery & Quality Standards',
    iconName: 'Clock',
    description: 'إدارة الجدول الزمني بدقة، مع التواصل الشفاف والدوري في كافة مراحل التطوير والتسليم المباشر.',
  },
];

export const SKILLS: Skill[] = [
  // Frontend
  {
    id: 'react',
    name: 'React 19 / Next.js',
    category: 'frontend',
    level: 96,
    iconName: 'Code',
    proficiencyLabel: 'خبير',
    highlights: ['Server Components', 'Custom Hooks', 'State Management'],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'frontend',
    level: 92,
    iconName: 'FileCode',
    proficiencyLabel: 'خبير',
    highlights: ['Strict Typing', 'Generics', 'System Interfaces'],
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS v4 & Glass Design',
    category: 'frontend',
    level: 98,
    iconName: 'Palette',
    proficiencyLabel: 'خبير',
    highlights: ['Backdrop Blur', 'Responsive Layouts', 'Custom Design Systems'],
  },
  {
    id: 'motion',
    name: 'Framer Motion / Motion',
    category: 'frontend',
    level: 90,
    iconName: 'Sparkles',
    proficiencyLabel: 'متقدم',
    highlights: ['Page Transitions', 'Gestures', 'RTL Layout Animations'],
  },
  {
    id: 'vue',
    name: 'Vue.js / Nuxt',
    category: 'frontend',
    level: 84,
    iconName: 'Layers',
    proficiencyLabel: 'متقن',
    highlights: ['Pinia Store', 'Composition API'],
  },

  // Backend
  {
    id: 'nodejs',
    name: 'Node.js & Express',
    category: 'backend',
    level: 88,
    iconName: 'Server',
    proficiencyLabel: 'متقدم',
    highlights: ['REST APIs', 'Middleware Architecture', 'Authentication'],
  },
  {
    id: 'graphql',
    name: 'GraphQL & Apollo',
    category: 'backend',
    level: 82,
    iconName: 'Cpu',
    proficiencyLabel: 'متقن',
    highlights: ['Schemas', 'Resolvers', 'Query Optimization'],
  },
  {
    id: 'databases',
    name: 'PostgreSQL / Prisma / Firestore',
    category: 'backend',
    level: 85,
    iconName: 'Database',
    proficiencyLabel: 'متقدم',
    highlights: ['ORM Integration', 'Realtime Listeners', 'Indexing'],
  },

  // Tools & UI
  {
    id: 'figma',
    name: 'Figma UI/UX & Glass Tokens',
    category: 'tools',
    level: 95,
    iconName: 'Figma',
    proficiencyLabel: 'خبير',
    highlights: ['Design Systems', 'Auto Layout', 'Interactive Prototypes'],
  },
  {
    id: 'git',
    name: 'Git / GitHub Enterprise',
    category: 'tools',
    level: 94,
    iconName: 'GitBranch',
    proficiencyLabel: 'خبير',
    highlights: ['Branching Strategies', 'CI/CD Pipelines', 'Code Review'],
  },
  {
    id: 'performance',
    name: 'Web Performance & Lighthouse',
    category: 'tools',
    level: 91,
    iconName: 'Gauge',
    proficiencyLabel: 'خبير',
    highlights: ['Core Web Vitals', 'Asset Compression', 'Code Splitting'],
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'منصة "أثير" للذكاء الاصطناعي وإدارة البيانات',
    category: 'ai',
    categoryLabel: 'الذكاء الاصطناعي',
    shortDescription: 'لوحة تحكم زجاجية تفاعلية لتحليل البيانات الضخمة والاستعلام الذكي بلغة طبيعية.',
    fullDescription: 'منصة "أثير" هي حل برمجي متكامل يعتمد على أحدث نماذج الذكاء الاصطناعي للتحليل الفوري واستخراج المؤشرات الاستراتيجية. تم تصميم الواجهة بنمط زجاجي داكن وتفاعلات استجابية لحظية مع دعم تقارير PDF ورسوم بيانية dynamic.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    tags: ['React 19', 'Tailwind CSS', 'Gemini API', 'Recharts', 'TypeScript'],
    demoUrl: 'https://example.com/atheer',
    githubUrl: 'https://github.com',
    highlights: [
      'سرعة استجابة فائقة بفضل تقليل زمن الاستعلام بنسبة 60%',
      'دعم نظام الوضع الزجاجي المتكيف مع شاشات 4K',
      'رسوم بيانية تفاعلية تدعم التمرير والدقة العالية',
      'تجهيز كامل للغة العربية ودعم اتجاه RTL بمرونة',
    ],
    metrics: 'زيادة إنتاجية فرق العمل بنسبة 45% وتوفير ساعتين يومياً من إعداد التقارير',
    year: '2026',
  },
  {
    id: 'p2',
    title: 'تطبيق "مدار" للمحفظة الاستثمارية والتداول',
    category: 'mobile',
    categoryLabel: 'تطبيقات الهواتف',
    shortDescription: 'تطبيق هاتف ذكي مالي ذو طابع زجاجي فاخر لمتابعة العملات والأسهم والأسواق المالية.',
    fullDescription: 'تطبيق جوال يتيح للمستثمرين متابعة محافظهم المالية في الوقت الفعلي مع تنبيهات ذكية وتصاميم زجاجية شبه شفافة تقلل الإجهاد البصري أثناء التداول السريع.',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    tags: ['React Native', 'TypeScript', 'Tailwind', 'WebSocket', 'Redux Toolkit'],
    demoUrl: 'https://example.com/madar',
    githubUrl: 'https://github.com',
    highlights: [
      'تزامن بيانات مباشر عبر WebSocket بسرعة 50ms',
      'حماية عالية بتشغيل البصمة وزجاج داكن مريح للعين',
      'مؤشرات وتنبيهات مخصصة للهواتف الذكية',
    ],
    metrics: 'أكثر من 150 ألف تحميل ونسبة تقييم 4.9 في المتاجر',
    year: '2025',
  },
  {
    id: 'p3',
    title: 'بوابة "سند" للخدمات السحابية وإدارة العقود',
    category: 'web',
    categoryLabel: 'تطبيقات الويب',
    shortDescription: 'منصة ويب متكاملة لإدارة المشاريع والعقود الإلكترونية بالتوقيع الرقمي.',
    fullDescription: 'نظام سحابي مرن يسهل أتمتة العقود والمستندات الرسمية للشركات والمؤسسات. تم تطوير النظام بأسلوب زجاجي حديث مع وحدات فلترة المجموعات وتصفح آمن للغاية.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Next.js', 'PostgreSQL', 'Tailwind', 'Node.js', 'PDF Engine'],
    demoUrl: 'https://example.com/sanad',
    githubUrl: 'https://github.com',
    highlights: [
      'أتمتة كاملة لدورة التوقيع الإلكتروني وتتبع الحالة',
      'تكامل مع البوابات الحكومية والتحقق الرقمي',
      'سجل مراجعة وتتبع آمن وتدقيق شامل للعمليات',
    ],
    metrics: 'معالجة أكثر من 50,000 عقد إلكتروني بدون أي توقف',
    year: '2025',
  },
  {
    id: 'p4',
    title: 'نظام تصميم "زجاج" (Zajaj UI System)',
    category: 'uiux',
    categoryLabel: 'تصميم واجهات UI/UX',
    shortDescription: 'مكتبة مكونات واجهات مستخدم زجاجية باللغة العربية مخصصة لمنصات SaaS الحديثة.',
    fullDescription: 'مكتبة تصميمية متكاملة تشتمل على أكثر من 80 مكوناً زجاجياً مستجيباً مع دعم كامل لاتجاه اليمين إلى اليسار RTL والتجاوب التام مع مختلف القياسات والأجهزة.',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Figma Tokens', 'React Components', 'Tailwind CSS', 'Storybook', 'Accessibility'],
    demoUrl: 'https://example.com/zajaj',
    githubUrl: 'https://github.com',
    highlights: [
      'تطبيق معايير إمكانية الوصول WCAG 2.1 AAA',
      'ملاحظات لمسية وحركية ملساء باستخدام Framer Motion',
      'توفير 40% من وقت البرمجة لفرق التطوير',
    ],
    metrics: 'تبني المكتبة من قبل 12 فريق تطوير محلي وإقليمي',
    year: '2026',
  },
  {
    id: 'p5',
    title: 'تطبيق "نبض" للرعاية الصحية والاستشارات الطبية',
    category: 'mobile',
    categoryLabel: 'تطبيقات الهواتف',
    shortDescription: 'منصة رعاية صحية ذكية تجمع بين حجز المواعيد والاستشارات الطبية المرئية.',
    fullDescription: 'تطبيق يربط المرضى بالاستشاريين المعتمدين مع غرف محادثة ومكالمات فيديو عالية النقاء وواجهات زجاجية دافئة تنعش تجربة المستخدم.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    tags: ['React Native', 'WebRTC', 'Node.js', 'Firebase', 'Tailwind'],
    demoUrl: 'https://example.com/nabdh',
    githubUrl: 'https://github.com',
    highlights: [
      'استشارات مرئية بتقنية WebRTC مشفرة بالكامل',
      'تذكيرات المواعيد والجرعات الدوائية بتنبيهات ذكية',
      'ملف صحي زجاجي تفاعلي يستعرض التحاليل والأشعة',
    ],
    metrics: 'خدمة أكثر من 80,000 استشارة طبية ناجحة',
    year: '2024',
  },
  {
    id: 'p6',
    title: 'مساعد "رؤية" للتجارة الإلكترونية والتوصيات',
    category: 'ai',
    categoryLabel: 'الذكاء الاصطناعي',
    shortDescription: 'محرك توصيات ذكي واختبار ملابس افتراضي للمتاجر الإلكترونية الكبرى.',
    fullDescription: 'محرك ذكاء اصطناعي مدمج في المتاجر الإلكترونية يحلل تفضيلات المتسوق ويوفر اقتراحات فورية مع واجهة تفاعلية شاشاتها زجاجية متطورة.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    tags: ['Python / Fast API', 'React 19', 'Tailwind v4', 'TensorFlow', 'Gemini'],
    demoUrl: 'https://example.com/roya',
    githubUrl: 'https://github.com',
    highlights: [
      'زيادة معدل السلة الشرائية بنسبة 35%',
      'توصيات شخصية فائقة الدقة خلال أقل من 100 ملي ثانية',
      'تكامل سلس مع منصات زد وسلة وShopify',
    ],
    metrics: 'رفع مبيعات المتجر الشريك بنسبة 28% خلال 3 أشهر',
    year: '2025',
  },
];

export const EXPERIENCES: ExperienceItem[] = [
  {
    id: 'e1',
    type: 'work',
    yearRange: '2023 - الحاضر',
    title: 'كبير مهندسي الواجهات (Principal Frontend Architect)',
    organization: 'شركة التقنيات الذكية المتقدمة | الرياض',
    location: 'الرياض، السعودية',
    description: 'قيادة فريق تطوير الواجهات لبناء منصات سحابية ضخمة بالنمط الزجاجي، والإشراف على نظام التصميم المؤسسي وتطبيق معايير السرعة والأمان.',
    keyAchievements: [
      'إعادة أتمتة بنية منصة الشركة الرئيسية وتحسين سرعة التحميل بنسبة 55%',
      'بناء نظام المكونات الزجاجية الموحد المستعمل في 8 منتجات رقمية',
      'تدريب وتوجيه 12 مهندس واجهات junior & mid-level',
    ],
  },
  {
    id: 'e2',
    type: 'work',
    yearRange: '2021 - 2023',
    title: 'مطور واجهات كبار (Senior UI/UX Engineer)',
    organization: 'استوديو الحلول البرمجية الرقمية',
    location: 'الرياض، السعودية',
    description: 'تطوير تطبيقات React & Next.js عالية التعقيد لقطاعات الأعمال المالية والتعليمية مع التركيز على اتجاه RTL وجماليات الواجهات الحديثة.',
    keyAchievements: [
      'تطوير 14 مشروع ويب وتطبيق جوال بنجاح مع الالتزام التام بالمواعيد',
      'رفع تقييم أداء الواجهات في اختبارات Lighthouse إلى 98+',
      'دمج تقنيات الرسوم البيانية اللحظية والتحليلات المباشرة',
    ],
  },
  {
    id: 'e3',
    type: 'work',
    yearRange: '2019 - 2021',
    title: 'مطور واجهات أول (Frontend Developer)',
    organization: 'مؤسسة التقنية للتطوير البرمجي',
    location: 'جدة، السعودية',
    description: 'بناء واجهات مستخدم تفاعلية باستخدام React وJavaScript وTailwind CSS، وتحويل مخططات Figma إلى كود مستجيب وسريع.',
    keyAchievements: [
      'بناء أول مكتبة مكونات متوافقة مع متطلبات الوصول الشامل',
      'العمل المباشر مع فرق المنتجات لضمان تجربة مستخدم خالية من العوائق',
    ],
  },
  {
    id: 'e4',
    type: 'education',
    yearRange: '2015 - 2019',
    title: 'بكالوريوس علوم الحاسب والمعلومات (امتياز مع مرتبة الشرف)',
    organization: 'جامعة الملك سعود',
    location: 'الرياض، السعودية',
    description: 'التخصص في هندسة البرمجيات، شبكات الحاسب، وتصميم واجهات التفاعل بين الإنسان والحاسوب (HCI).',
    keyAchievements: [
      'مشروع التخرج: نظام ذكي للتنبؤ بالأخطاء البرمجية (درجة 100/100)',
      'رئيس نادي هندسة الحاسب والابتكار التقني في الجامعة',
    ],
  },
  {
    id: 'e5',
    type: 'education',
    yearRange: '2022',
    title: 'شهادة خبير معتمد في هندسة واجهات React & Cloud Systems',
    organization: 'AWS & Meta Certified Professional',
    location: 'أونلاين / دولي',
    description: 'اعتماد متقدم في بنية الأنظمة الموزعة للواجهات وإدارة الحالة المعقدة وتحسين الأداء.',
    keyAchievements: ['الاجتياز بدرجة 96%', 'شهادة معتمدة عالمياً'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'د. خالد العتيبي',
    role: 'الرئيس التنفيذي للتكنولوجيا',
    company: 'مجموعة المبتكرون الرقميون',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    quote: 'عبد الله ليس مجرد مبرمج واجهات، بل هو مهندس يفهم جوهر تجربة المستخدم. حوّل مشروع منصتنا الزجاجية إلى تحفة فنية فائقة السرعة.',
    rating: 5,
  },
  {
    id: 't2',
    name: 'أ. سارة السديري',
    role: 'مديرة قطاع المنتجات',
    company: 'حلول الويب الحديثة',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    quote: 'الدقة المتناهية والالتزام بالمواعيد هي العنوان الأبرز في التعامل مع المهندس عبد الله. كوده متسق للغاية وسهل التطوير مستقبلاً.',
    rating: 5,
  },
  {
    id: 't3',
    name: 'م. فهد العنزي',
    role: 'مؤسس ورئيس مجلس الإدارة',
    company: 'شركة أثير الذكية',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    quote: 'من أفضل من تعاملت معهم في هندسة الواجهات التفاعلية العربية. الجمالية الزجاجية والدعم التام لـ RTL أذهل المستثمرين والمستخدمين.',
    rating: 5,
  },
];
